apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: developerpawel/mimenu-patient
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: mimenu
            - name: MONGO_URI
              value: mongodb://patient-mongo-srv:27017/patient
---
apiVersion: v1
kind: Service
metadata:
  name: patient-srv
spec:
  selector:
    app: patient
  ports:
    - name: patient
      protocol: TCP
      port: 3000
      targetPort: 3000
