name: test-admin

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - run: cd admin && npm install && npm run test:ci
