name: test-client-provider

on:
  pull_request:
    paths:
      - "client/provider/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/provider && npm ci
      - run: npm run test:ci
