name: test-client-auth

on:
  pull_request:
    paths:
      - "client/auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/auth && npm install && npm run test:ci
        env:
          CI: false
