name: test-patient

on:
  pull_request:
    paths:
      - "patient/**"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - run: cd patient && npm install && npm run test:ci
