name: test-client-container

on:
  pull_request:
    paths:
      - "client/container/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/container && npm install && npm run test:ci
