name: test-client-common

on:
  pull_request:
    paths:
      - "client/common/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/common && npm install && npm run test:ci
